// JMX Converter Utility

function generateJMX(requests) {
  if (!requests || requests.length === 0) return '';

  // --- Pass 1: Analysis ---
  const domainMap = analyzeDomains(requests);
  const commonHeaders = analyzeHeaders(requests);

  // --- Pass 2: Generation ---
  const testPlanVariables = generateUserDefinedVariables(domainMap);
  const globalConfig = createGlobalConfig(commonHeaders);

  const header = `<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.3">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Recorded Test Plan" enabled="true">
      <stringProp name="TestPlan.comments">Generated by Chrome Extension</stringProp>
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
        <collectionProp name="Arguments.arguments">
          ${testPlanVariables}
        </collectionProp>
      </elementProp>
      <stringProp name="TestPlan.user_define_classpath"></stringProp>
    </TestPlan>
    <hashTree>
      ${globalConfig}
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Thread Group" enabled="true">
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <stringProp name="LoopController.loops">1</stringProp>
        </elementProp>
        <stringProp name="ThreadGroup.num_threads">1</stringProp>
        <stringProp name="ThreadGroup.ramp_time">1</stringProp>
        <boolProp name="ThreadGroup.scheduler">false</boolProp>
        <stringProp name="ThreadGroup.duration"></stringProp>
        <stringProp name="ThreadGroup.delay"></stringProp>
        <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
      </ThreadGroup>
      <hashTree>
`;

  const footer = `
      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan>`;

  // Group requests by step
  const groupedRequests = [];
  let currentGroup = null;

  requests.forEach(req => {
    const stepName = req.step || 'Init';
    if (!currentGroup || currentGroup.name !== stepName) {
      currentGroup = { name: stepName, requests: [] };
      groupedRequests.push(currentGroup);
    }
    currentGroup.requests.push(req);
  });

  let content = '';
  let previousTimestamp = requests[0].timeStamp;

  groupedRequests.forEach(group => {
    content += createTransactionController(group, domainMap, commonHeaders, previousTimestamp);
    // Update timestamp for the next group to be the end of this group
    if (group.requests.length > 0) {
      previousTimestamp = group.requests[group.requests.length - 1].timeStamp;
    }
  });

  return header + content + footer;
}

// --- Analysis Functions ---

function analyzeDomains(requests) {
  const domains = new Set();
  requests.forEach(req => {
    try {
      const url = new URL(req.url);
      domains.add(url.hostname);
    } catch (e) { }
  });

  const domainMap = {};
  let counter = 1;
  domains.forEach(domain => {
    domainMap[domain] = `BASE_URL_${counter++}`;
  });
  return domainMap;
}

function analyzeHeaders(requests) {
  const headerCounts = {};
  const totalRequests = requests.length;

  requests.forEach(req => {
    if (req.requestHeaders) {
      req.requestHeaders.forEach(h => {
        const name = h.name;
        const value = h.value;
        const key = `${name}|${value}`;

        if (!headerCounts[key]) {
          headerCounts[key] = { name, value, count: 0 };
        }
        headerCounts[key].count++;
      });
    }
  });

  const commonHeaders = [];
  // If a header (name+value) appears in > 80% of requests, make it global
  const threshold = totalRequests * 0.8;

  for (const key in headerCounts) {
    if (headerCounts[key].count >= threshold) {
      // Exclude dynamic headers usually
      if (!['Content-Length', 'Host', 'Connection', 'Cookie', 'Referer'].includes(headerCounts[key].name)) {
        commonHeaders.push(headerCounts[key]);
      }
    }
  }
  return commonHeaders;
}

// --- Generation Functions ---

function generateUserDefinedVariables(domainMap) {
  let xml = '';
  for (const [domain, varName] of Object.entries(domainMap)) {
    xml += `
          <elementProp name="${varName}" elementType="Argument">
            <stringProp name="Argument.name">${varName}</stringProp>
            <stringProp name="Argument.value">${domain}</stringProp>
            <stringProp name="Argument.metadata">=</stringProp>
          </elementProp>`;
  }
  return xml;
}

function createGlobalConfig(commonHeaders) {
  let headersXml = '';
  commonHeaders.forEach(h => {
    headersXml += `
          <elementProp name="" elementType="Header">
            <stringProp name="Header.name">${escapeXml(h.name)}</stringProp>
            <stringProp name="Header.value">${escapeXml(h.value)}</stringProp>
          </elementProp>`;
  });

  return `
      <HeaderManager guiclass="HeaderPanel" testclass="HeaderManager" testname="HTTP Header Manager" enabled="true">
        <collectionProp name="HeaderManager.headers">
          ${headersXml}
        </collectionProp>
      </HeaderManager>
      <hashTree/>
      <CookieManager guiclass="CookiePanel" testclass="CookieManager" testname="HTTP Cookie Manager" enabled="true">
        <collectionProp name="CookieManager.cookies"/>
        <boolProp name="CookieManager.clearEachIteration">true</boolProp>
        <boolProp name="CookieManager.controlledByThreadGroup">false</boolProp>
      </CookieManager>
      <hashTree/>
      <CacheManager guiclass="CacheManagerGui" testclass="CacheManager" testname="HTTP Cache Manager" enabled="true">
        <boolProp name="clearEachIteration">true</boolProp>
        <boolProp name="useExpires">true</boolProp>
        <boolProp name="CacheManager.controlledByThread">false</boolProp>
      </CacheManager>
      <hashTree/>
      <DNSCacheManager guiclass="DNSCachePanel" testclass="DNSCacheManager" testname="DNS Cache Manager" enabled="true">
        <collectionProp name="DNSCacheManager.servers"/>
        <boolProp name="DNSCacheManager.clearEachIteration">true</boolProp>
        <boolProp name="DNSCacheManager.isCustomResolver">false</boolProp>
      </DNSCacheManager>
      <hashTree/>
      <AuthManager guiclass="AuthPanel" testclass="AuthManager" testname="HTTP Authorization Manager" enabled="true">
        <collectionProp name="AuthManager.auth_list"/>
        <boolProp name="AuthManager.controlledByThreadGroup">false</boolProp>
      </AuthManager>
      <hashTree/>
      <ConfigTestElement guiclass="HttpDefaultsGui" testclass="ConfigTestElement" testname="HTTP Request Defaults" enabled="true">
        <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" enabled="true">
          <collectionProp name="Arguments.arguments"/>
        </elementProp>
        <stringProp name="HTTPSampler.implementation">HttpClient4</stringProp>
      </ConfigTestElement>
      <hashTree/>
    `;
}

function createTransactionController(group, domainMap, commonHeaders, previousTimestamp) {
  let samplers = '';

  group.requests.forEach((req, index) => {
    samplers += createHTTPSampler(req, domainMap, commonHeaders);
  });

  return `
        <TransactionController guiclass="TransactionControllerGui" testclass="TransactionController" testname="${escapeXml(group.name)}" enabled="true">
          <boolProp name="TransactionController.includeTimers">false</boolProp>
          <boolProp name="TransactionController.parent">true</boolProp>
        </TransactionController>
        <hashTree>
            ${samplers}
        </hashTree>
    `;
}

function createHTTPSampler(req, domainMap, commonHeaders) {
  let url;
  try {
    url = new URL(req.url);
  } catch (e) {
    console.warn("Invalid URL:", req.url);
    return ''; // Skip invalid URLs
  }

  const protocol = url.protocol.replace(':', '');
  const domain = url.hostname;
  const port = url.port; // Leave empty if default
  const path = url.pathname;
  const method = req.method;
  const queryParams = url.searchParams;

  // Use Variable for Domain
  const domainVar = domainMap[domain] ? `\${${domainMap[domain]}}` : domain;

  let argumentsXml = '';
  let hasBody = false;

  // Handle POST Body
  if (req.method === 'POST' || req.method === 'PUT' || req.method === 'PATCH') {
    if (req.requestBody) {
      if (req.requestBody.raw && req.requestBody.raw.length > 0) {
        // Raw Body (JSON, etc)
        let rawData = '';
        const rawObj = req.requestBody.raw[0];

        if (rawObj.bytes) {
          try {
            // Check if bytes is an ArrayBuffer or similar
            if (rawObj.bytes instanceof ArrayBuffer) {
              rawData = new TextDecoder().decode(new Uint8Array(rawObj.bytes));
            } else if (typeof rawObj.bytes === 'object' && Object.keys(rawObj.bytes).length === 0) {
              // Empty object from storage deserialization of ArrayBuffer
              rawData = '';
            } else {
              // Fallback or unexpected type
              rawData = '';
            }
          } catch (e) {
            console.warn("Failed to decode raw body bytes", e);
          }
        } else if (rawObj.file) {
          rawData = rawObj.file;
        }

        argumentsXml = `
                <boolProp name="HTTPSampler.postBodyRaw">true</boolProp>
                <elementProp name="HTTPsampler.Arguments" elementType="Arguments">
                  <collectionProp name="Arguments.arguments">
                    <elementProp name="" elementType="HTTPArgument">
                      <boolProp name="HTTPArgument.always_encode">false</boolProp>
                      <stringProp name="Argument.value">${escapeXml(rawData)}</stringProp>
                      <stringProp name="Argument.metadata">=</stringProp>
                    </elementProp>
                  </collectionProp>
                </elementProp>`;
        hasBody = true;
      } else if (req.requestBody.formData) {
        // Form Data
        let args = '';
        for (const key in req.requestBody.formData) {
          const value = req.requestBody.formData[key][0];
          args += `
                    <elementProp name="${escapeXml(key)}" elementType="HTTPArgument">
                      <boolProp name="HTTPArgument.always_encode">true</boolProp>
                      <stringProp name="Argument.value">${escapeXml(value)}</stringProp>
                      <stringProp name="Argument.metadata">=</stringProp>
                      <boolProp name="HTTPArgument.use_equals">true</boolProp>
                      <stringProp name="Argument.name">${escapeXml(key)}</stringProp>
                    </elementProp>`;
        }
        argumentsXml = `
                <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" enabled="true">
                  <collectionProp name="Arguments.arguments">${args}</collectionProp>
                </elementProp>`;
        hasBody = true;
      }
    }
  }

  // If no body arguments yet, use query params
  if (!hasBody) {
    let args = '';
    queryParams.forEach((value, key) => {
      args += `
            <elementProp name="${escapeXml(key)}" elementType="HTTPArgument">
              <boolProp name="HTTPArgument.always_encode">true</boolProp>
              <stringProp name="Argument.value">${escapeXml(value)}</stringProp>
              <stringProp name="Argument.metadata">=</stringProp>
              <boolProp name="HTTPArgument.use_equals">true</boolProp>
              <stringProp name="Argument.name">${escapeXml(key)}</stringProp>
            </elementProp>`;
    });
    argumentsXml = `
        <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" enabled="true">
          <collectionProp name="Arguments.arguments">${args}</collectionProp>
        </elementProp>`;
  }

  // Header Manager (Local)
  let headerManager = '';
  if (req.requestHeaders && req.requestHeaders.length > 0) {
    let headers = '';
    let hasLocalHeaders = false;

    req.requestHeaders.forEach(h => {
      // Skip if it's a common global header
      const isCommon = commonHeaders.some(ch => ch.name === h.name && ch.value === h.value);
      // Skip auto-generated headers
      const isAuto = ['Host', 'Content-Length', 'Connection'].includes(h.name);

      if (!isCommon && !isAuto) {
        headers += `
                <elementProp name="" elementType="Header">
                  <stringProp name="Header.name">${escapeXml(h.name)}</stringProp>
                  <stringProp name="Header.value">${escapeXml(h.value)}</stringProp>
                </elementProp>`;
        hasLocalHeaders = true;
      }
    });

    if (hasLocalHeaders) {
      headerManager = `
            <HeaderManager guiclass="HeaderPanel" testclass="HeaderManager" testname="HTTP Header Manager" enabled="true">
              <collectionProp name="HeaderManager.headers">
                ${headers}
              </collectionProp>
            </HeaderManager>
            <hashTree/>`;
    }
  }

  return `
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="${escapeXml(method)} ${escapeXml(path)}" enabled="true">
          ${argumentsXml}
          <stringProp name="HTTPSampler.domain">${escapeXml(domainVar)}</stringProp>
          <stringProp name="HTTPSampler.port">${escapeXml(port)}</stringProp>
          <stringProp name="HTTPSampler.protocol">${escapeXml(protocol)}</stringProp>
          <stringProp name="HTTPSampler.path">${escapeXml(path)}</stringProp>
          <stringProp name="HTTPSampler.method">${escapeXml(method)}</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
          <stringProp name="HTTPSampler.connect_timeout"></stringProp>
          <stringProp name="HTTPSampler.response_timeout"></stringProp>
        </HTTPSamplerProxy>
        <hashTree>
            ${headerManager}
        </hashTree>
    `;
}

function escapeXml(unsafe) {
  if (unsafe === null || unsafe === undefined) return '';
  return String(unsafe).replace(/[<>&'"]/g, function (c) {
    switch (c) {
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '&': return '&amp;';
      case '\'': return '&apos;';
      case '"': return '&quot;';
    }
  });
}
